# Turn on validation, so we can use import:
version: ~> 1.0

jdk:
- openjdk8

services:
- docker

import: land-of-apps/land-of-apps:travis/java-imports.yml

before_install:
- curl -fsSL https://api.github.com/repos/confluentinc/cp-all-in-one/contents/cp-all-in-one/docker-compose.yml?ref=5.5.1-post   | jq -r .content | base64 --decode > docker-compose.yml

before_script:
- docker-compose up -d

script:
- ls
